//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 11:30:16 AM CST 
//


package org.pseudoscript.script.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for argument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="argument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="simpleData" type="{http://www.pseudoscript.org/Script}simpleData"/>
 *         &lt;element name="referredData" type="{http://www.pseudoscript.org/Script}referredData"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "argument", propOrder = {
    "simpleData",
    "referredData"
})
public class Argument {

    protected SimpleData simpleData;
    protected ReferredData referredData;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the simpleData property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleData }
     *     
     */
    public SimpleData getSimpleData() {
        return simpleData;
    }

    /**
     * Sets the value of the simpleData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleData }
     *     
     */
    public void setSimpleData(SimpleData value) {
        this.simpleData = value;
    }

    /**
     * Gets the value of the referredData property.
     * 
     * @return
     *     possible object is
     *     {@link ReferredData }
     *     
     */
    public ReferredData getReferredData() {
        return referredData;
    }

    /**
     * Sets the value of the referredData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferredData }
     *     
     */
    public void setReferredData(ReferredData value) {
        this.referredData = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
