//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 11:30:16 AM CST 
//


package org.pseudoscript.script.xml.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.pseudoscript.script.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Script_QNAME = new QName("http://www.pseudoscript.org/Script", "script");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.pseudoscript.script.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Argument }
     * 
     */
    public Argument createArgument() {
        return new Argument();
    }

    /**
     * Create an instance of {@link SimpleData }
     * 
     */
    public SimpleData createSimpleData() {
        return new SimpleData();
    }

    /**
     * Create an instance of {@link ReferredData }
     * 
     */
    public ReferredData createReferredData() {
        return new ReferredData();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Operation.Arguments }
     * 
     */
    public Operation.Arguments createOperationArguments() {
        return new Operation.Arguments();
    }

    /**
     * Create an instance of {@link Script.DataSources }
     * 
     */
    public Script.DataSources createScriptDataSources() {
        return new Script.DataSources();
    }

    /**
     * Create an instance of {@link Script.Operations }
     * 
     */
    public Script.Operations createScriptOperations() {
        return new Script.Operations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Script }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.pseudoscript.org/Script", name = "script")
    public JAXBElement<Script> createScript(Script value) {
        return new JAXBElement<Script>(_Script_QNAME, Script.class, null, value);
    }

}
